# Form implementation generated from reading ui file 'd:\TDLT_K24411TE\bmi\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 500)
        MainWindow.setMinimumSize(QtCore.QSize(420, 450))
        MainWindow.setStyleSheet("\n"
"/* ===== Global Window ===== */\n"
"QMainWindow {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"/* ===== Central Card ===== */\n"
"#centralwidget {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"/* ===== Header Label ===== */\n"
"#label {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #667eea, stop:1 #764ba2);\n"
"    color: #ffffff;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"/* ===== Form Labels ===== */\n"
"#label_2, #label_3, #label_4, #label_5, #label_6, #label_7, #label_10 {\n"
"    color: #4a4a68;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* ===== Input Fields ===== */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    color: #1f2937;\n"
"    selection-background-color: #667eea;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667eea;\n"
"}\n"
"\n"
"/* ===== Result Card (BMI value) ===== */\n"
"#labelBMI {\n"
"    background-color: #eef2ff;\n"
"    border: 2px solid #667eea;\n"
"    border-radius: 8px;\n"
"    padding: 4px 12px;\n"
"    color: #4338ca;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== Comment Card ===== */\n"
"#labelComment {\n"
"    background-color: #fef2f2;\n"
"    border: 2px solid #f87171;\n"
"    border-radius: 8px;\n"
"    padding: 4px 12px;\n"
"    color: #dc2626;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== Calculate Button ===== */\n"
"#pushButtonCalculate {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #667eea, stop:1 #764ba2);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px 24px;\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"}\n"
"#pushButtonCalculate:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #5a6fd6, stop:1 #6a4194);\n"
"}\n"
"#pushButtonCalculate:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #4f5fc2, stop:1 #5e3986);\n"
"}\n"
"\n"
"/* ===== Close Button ===== */\n"
"#pushButtonClose {\n"
"    background-color: #ffffff;\n"
"    color: #6b7280;\n"
"    border: 2px solid #d1d5db;\n"
"    border-radius: 10px;\n"
"    padding: 10px 24px;\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"}\n"
"#pushButtonClose:hover {\n"
"    background-color: #f9fafb;\n"
"    border-color: #9ca3af;\n"
"    color: #374151;\n"
"}\n"
"#pushButtonClose:pressed {\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"/* ===== Status Bar ===== */\n"
"QStatusBar {\n"
"    background-color: #e5e7eb;\n"
"    color: #6b7280;\n"
"    font-size: 9pt;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setContentsMargins(24, 16, 24, 16)
        self.mainVerticalLayout.setSpacing(16)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 56))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.mainVerticalLayout.addWidget(self.label)
        self.inputGrid = QtWidgets.QGridLayout()
        self.inputGrid.setHorizontalSpacing(12)
        self.inputGrid.setVerticalSpacing(14)
        self.inputGrid.setObjectName("inputGrid")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputGrid.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditWeight = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditWeight.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditWeight.setFont(font)
        self.lineEditWeight.setObjectName("lineEditWeight")
        self.inputGrid.addWidget(self.lineEditWeight, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.inputGrid.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputGrid.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEditHeight = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditHeight.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditHeight.setFont(font)
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.inputGrid.addWidget(self.lineEditHeight, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.inputGrid.addWidget(self.label_4, 1, 2, 1, 1)
        self.mainVerticalLayout.addLayout(self.inputGrid)
        self.separator = QtWidgets.QFrame(parent=self.centralwidget)
        self.separator.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator.setStyleSheet("color: #d1d5db;")
        self.separator.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.separator.setObjectName("separator")
        self.mainVerticalLayout.addWidget(self.separator)
        self.resultGrid = QtWidgets.QGridLayout()
        self.resultGrid.setHorizontalSpacing(12)
        self.resultGrid.setVerticalSpacing(14)
        self.resultGrid.setObjectName("resultGrid")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.resultGrid.addWidget(self.label_6, 0, 0, 1, 1)
        self.labelBMI = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBMI.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelBMI.setFont(font)
        self.labelBMI.setObjectName("labelBMI")
        self.resultGrid.addWidget(self.labelBMI, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.resultGrid.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.resultGrid.addWidget(self.label_7, 1, 0, 1, 1)
        self.labelComment = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelComment.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelComment.setFont(font)
        self.labelComment.setObjectName("labelComment")
        self.resultGrid.addWidget(self.labelComment, 1, 1, 1, 2)
        self.mainVerticalLayout.addLayout(self.resultGrid)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainVerticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(16)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setMinimumSize(QtCore.QSize(160, 48))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\TDLT_K24411TE\\bmi\\images/ic_calculate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCalculate.setIcon(icon)
        self.pushButtonCalculate.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.buttonLayout.addWidget(self.pushButtonCalculate)
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(160, 48))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\TDLT_K24411TE\\bmi\\images/ic_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClose.setIcon(icon1)
        self.pushButtonClose.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.buttonLayout.addWidget(self.pushButtonClose)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.mainVerticalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonClose.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMI Calculator — Hoàng Phương Anh"))
        self.label.setText(_translate("MainWindow", "🏋️  BMI Calculator"))
        self.label_2.setText(_translate("MainWindow", "Weight:"))
        self.lineEditWeight.setPlaceholderText(_translate("MainWindow", "Enter weight…"))
        self.lineEditWeight.setText(_translate("MainWindow", "80"))
        self.label_3.setText(_translate("MainWindow", "kg"))
        self.label_5.setText(_translate("MainWindow", "Height:"))
        self.lineEditHeight.setPlaceholderText(_translate("MainWindow", "Enter height…"))
        self.lineEditHeight.setText(_translate("MainWindow", "170"))
        self.label_4.setText(_translate("MainWindow", "cm"))
        self.label_6.setText(_translate("MainWindow", "BMI:"))
        self.labelBMI.setText(_translate("MainWindow", "—"))
        self.label_10.setText(_translate("MainWindow", "kg/m²"))
        self.label_7.setText(_translate("MainWindow", "Result:"))
        self.labelComment.setText(_translate("MainWindow", "—"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "  Calculate"))
        self.pushButtonClose.setText(_translate("MainWindow", "  Close"))
