# Form implementation generated from reading ui file 'D:\TDLT_K24411TE\Chapter5\Ex73\ui\MyMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.equationLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.equationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.equationLabel.setObjectName("equationLabel")
        self.verticalLayout.addWidget(self.equationLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.aLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.aLabel.setObjectName("aLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.aLabel)
        self.aLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.aLineEdit.setObjectName("aLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.aLineEdit)
        self.bLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.bLabel.setObjectName("bLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.bLabel)
        self.bLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.bLineEdit.setObjectName("bLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bLineEdit)
        self.cLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.cLabel.setObjectName("cLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cLineEdit.setObjectName("cLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cLineEdit)
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.resultLabel)
        self.resultLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.resultLineEdit.setReadOnly(True)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.resultLineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exercise 73 - Quadratic Equation"))
        self.label.setText(_translate("MainWindow", "Quadratic Equation"))
        self.equationLabel.setText(_translate("MainWindow", "ax² + bx + c = 0"))
        self.aLabel.setText(_translate("MainWindow", "a:"))
        self.bLabel.setText(_translate("MainWindow", "b:"))
        self.cLabel.setText(_translate("MainWindow", "c:"))
        self.resultLabel.setText(_translate("MainWindow", "Result:"))
        self.pushButton.setText(_translate("MainWindow", "Solve"))
