# Form implementation generated from reading ui file 'D:\TDLT_K24411TE\Ex82\ui\Ex82MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 440)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 661, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"background-color: rgb(170, 255, 255);\n"
"border: 1px solid rgb(0, 0, 255);\n"
"margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 10px;\n"
"color: rgb(0, 0, 255);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.customerNameLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.customerNameLabel.setGeometry(QtCore.QRect(20, 35, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.customerNameLabel.setFont(font)
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.customerNameLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.customerNameLineEdit.setGeometry(QtCore.QRect(200, 35, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.customerNameLineEdit.setFont(font)
        self.customerNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.customerNameLineEdit.setObjectName("customerNameLineEdit")
        self.customerGroupLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.customerGroupLabel.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.customerGroupLabel.setFont(font)
        self.customerGroupLabel.setObjectName("customerGroupLabel")
        self.customerGroupComboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.customerGroupComboBox.setGeometry(QtCore.QRect(200, 80, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.customerGroupComboBox.setFont(font)
        self.customerGroupComboBox.setObjectName("customerGroupComboBox")
        self.customerGroupComboBox.addItem("")
        self.customerGroupComboBox.addItem("")
        self.kwhLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.kwhLabel.setGeometry(QtCore.QRect(20, 125, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.kwhLabel.setFont(font)
        self.kwhLabel.setObjectName("kwhLabel")
        self.kwhLineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.kwhLineEdit.setGeometry(QtCore.QRect(200, 125, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kwhLineEdit.setFont(font)
        self.kwhLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.kwhLineEdit.setObjectName("kwhLineEdit")
        self.pushButton_calc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_calc.setGeometry(QtCore.QRect(118, 245, 141, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_calc.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\TDLT_K24411TE\\Ex82\\ui\\../images/calculator.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_calc.setIcon(icon)
        self.pushButton_calc.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(279, 245, 141, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_clear.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\TDLT_K24411TE\\Ex82\\ui\\../images/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_clear.setIcon(icon1)
        self.pushButton_clear.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(440, 245, 141, 45))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_exit.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\TDLT_K24411TE\\Ex82\\ui\\../images/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_exit.setIcon(icon2)
        self.pushButton_exit.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 305, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"background-color: rgb(213, 255, 61);\n"
"border: 1px solid rgb(0, 0, 255);\n"
"margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"left: 10px;\n"
"color: rgb(0, 0, 255);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.amountLabel = QtWidgets.QLabel(parent=self.groupBox_2)
        self.amountLabel.setGeometry(QtCore.QRect(20, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.amountLabel.setFont(font)
        self.amountLabel.setObjectName("amountLabel")
        self.amountLineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.amountLineEdit.setGeometry(QtCore.QRect(240, 30, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.amountLineEdit.setFont(font)
        self.amountLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.amountLineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amountLineEdit.setReadOnly(True)
        self.amountLineEdit.setObjectName("amountLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.customerNameLineEdit, self.customerGroupComboBox)
        MainWindow.setTabOrder(self.customerGroupComboBox, self.kwhLineEdit)
        MainWindow.setTabOrder(self.kwhLineEdit, self.pushButton_calc)
        MainWindow.setTabOrder(self.pushButton_calc, self.pushButton_clear)
        MainWindow.setTabOrder(self.pushButton_clear, self.pushButton_exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hoang Phuong Anh - K244111451"))
        self.label.setText(_translate("MainWindow", "Electricity Bill System"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer Information:"))
        self.customerNameLabel.setText(_translate("MainWindow", "Customer name:"))
        self.customerNameLineEdit.setPlaceholderText(_translate("MainWindow", "Enter customer name here"))
        self.customerGroupLabel.setText(_translate("MainWindow", "Customer group:"))
        self.customerGroupComboBox.setItemText(0, _translate("MainWindow", "Retail price of household electricity"))
        self.customerGroupComboBox.setItemText(1, _translate("MainWindow", "Household using prepaid card meters"))
        self.kwhLabel.setText(_translate("MainWindow", "Number of kWh:"))
        self.kwhLineEdit.setPlaceholderText(_translate("MainWindow", "Enter number of kWh here"))
        self.pushButton_calc.setText(_translate("MainWindow", "&Calculate"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result:"))
        self.amountLabel.setText(_translate("MainWindow", "Amount to pay (VND):"))
